# Generated by Django 4.2.4 on 2023-08-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
    ]
